discography:
    path:     /
    defaults: { _controller: "MegalomanBundle:Discography:index" }

discography_show:
    path:     /{id}/show
    defaults: { _controller: "MegalomanBundle:Discography:show" }

discography_edit:
    path:     /{id}/edit
    defaults: { _controller: "MegalomanBundle:Discography:edit" }

discography_update:
    path:     /{id}/update
    defaults: { _controller: "MegalomanBundle:Discography:update" }
    requirements: { _method: post|put }

discography_search:
    path:     /{id}/search
    defaults: { _controller: "MegalomanBundle:Discography:search" }
    requirements: { _method: post }
