discography:
    path:     /
    defaults: { _controller: "MegalomanBundle:Discography:index" }

discography_show:
    path:     /{id}/show
    defaults: { _controller: "MegalomanBundle:Discography:show" }

discography_new:
    path:     /new
    defaults: { _controller: "MegalomanBundle:Discography:new" }

discography_create:
    path:     /create
    defaults: { _controller: "MegalomanBundle:Discography:create" }
    requirements: { _method: post }

discography_edit:
    path:     /{id}/edit
    defaults: { _controller: "MegalomanBundle:Discography:edit" }

discography_update:
    path:     /{id}/update
    defaults: { _controller: "MegalomanBundle:Discography:update" }
    requirements: { _method: post|put }

discography_delete:
    path:     /{id}/delete
    defaults: { _controller: "MegalomanBundle:Discography:delete" }
    requirements: { _method: post|delete }
