discography:
    path:     /
    defaults: { _controller: "MegalomanBundle:Discography:index" }

discography_show:
    path:     /{id}/show
    defaults: { _controller: "MegalomanBundle:Discography:show" }
