megaloman:
    path:     /
    defaults: { _controller: "MegalomanBundle:Megaloman:index" }

megaloman_show:
    path:     /{id}/show
    defaults: { _controller: "MegalomanBundle:Megaloman:show" }

megaloman_new:
    path:     /new
    defaults: { _controller: "MegalomanBundle:Megaloman:new" }

megaloman_create:
    path:     /create
    defaults: { _controller: "MegalomanBundle:Megaloman:create" }
    requirements: { _method: post }

megaloman_edit:
    path:     /{id}/edit
    defaults: { _controller: "MegalomanBundle:Megaloman:edit" }

megaloman_update:
    path:     /{id}/update
    defaults: { _controller: "MegalomanBundle:Megaloman:update" }
    requirements: { _method: post|put }

megaloman_delete:
    path:     /{id}/delete
    defaults: { _controller: "MegalomanBundle:Megaloman:delete" }
    requirements: { _method: post|delete }
