<?php

namespace PiotrK\MegalomanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MegalomanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MegalomanRepository extends EntityRepository
{
}
